project:
  type: website

website:
  title: "SMT201-Group 5"
  navbar:
    left:
      - href: "home.html"
        text: HOME
      - text: OVERVIEW
        href: "overview.html"
      - text: METHODOLOGY
        href: "methodology.html"
      - text: RESULT & DISCUSSION
        href: "analysis.html"
      - text: LESSON
        href: "lesson.html"
      - text: POSTER
        href: "poster.html"
    right:
      - text: ABOUT
        href: "about.html"
      
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

