project:
  type: website

website:
  title: "GROUP 5"
  navbar:
    left:
      - href: "index.html"
        text: HOME
      - text: OVERVIEW
        href: "overview.html"
      - text: METHODOLOGY
        href: "methodology.html"
      - text: RESULT & DISCUSSION
        menu:
        - text: Overall Analysis in Singapore
          href: "analysis.html"
        - text: Deep Dive into Lim Chu Kang 
          href: "limchukang.html"
      - text: LESSON LEARNED
        href: "lesson.html"
      - text: POSTER
        href: "poster.html"
    right:
      - text: ABOUT
        href: "about.html"
      
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

