---
title: "LESSONS LEARNED"
---

As this project is towards GIS-based Multi-criteria Analysis, or what we call Multiple-criteria Decision Analysis (MADM) for solar farm, there are multiple considerations to determine the land area for research. We need to consider the approach to uncover land use factors and as there are many different subzones that can be considered for solar farms installation, uncovering at least one of them will help consider factors that contribute to greater suitability assessment for other areas in Singapore. Lim Chu Kang has caught the attention of us due to its great factorial contributors that helped us determine it to be particularly suitable due to its huge spatial land area and even ground for solar farms, etc..

From our analysis, we can conclude that despite the consistent aspect suitability experienced in Singapore, surface irradiance involving sunlight and slope suitability are 2 of the factors that are viable to suggest suitability of solar farms. The installation of solar farms require lands that have the least slope and greater amount of sunlight, amongst many other factors. This can be attributed to the fact that Lim Chu Kang have been primarily used for commercial purposes and its place for army grounds and cemeteries. Additionally, the upcoming masterplan developments of Lim Chu Kang become a key enablement of Singapore to produce 30 per cent of nutritional needs by 2030 using solar panels in greenhouses for harnessing renewable energy and intensifying land use such as growing produce in underground caverns to guard against rising sea levels, these are potential areas that increase the suitability for Lim Chu Kang as the best land for research.

There are many other methods and factors to look out for, in which a research from the [Geography compass](https://www.researchgate.net/publication/227670445_GIS-Based_Multiple-Criteria_Decision_Analysis) suggest the use of waterdistance criterion and additional weight criterion for research purposes. Many ways have been conducted to analyse land cover factors for suitability of solar farms, but the change in weather conditions and global warming have outweigh the potential of consistent findings throughout researches. Our findings only contribute to a single subzone of Singapore, and along with many factors involve, we believe that in the future, more works can be done to accomplish what many have set along their path to do.
